/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ezeha
 */
public class DatabaseEditor extends javax.swing.JPanel {

    /**
     * Creates new form DatabaseView
     */
    private JFrame addDataWindow;
    
    public DatabaseEditor() {
        initComponents();
    }
    
    public void initTable(String[] columnNames, Object[][] rows, JFrame popupWindow){
        dbTable.setModel(new DefaultTableModel(rows, columnNames));
        addDataWindow = popupWindow;
        addButton.addActionListener(new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae){
            addDataWindow.setVisible(true);
        }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableScroll = new javax.swing.JScrollPane();
        dbTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableScroll.setViewportView(dbTable);

        add(TableScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 640, 370));

        addButton.setText("Add");
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 80, -1));

        removeButton.setText("Remove");
        add(removeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 80, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane TableScroll;
    private javax.swing.JButton addButton;
    private javax.swing.JTable dbTable;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
