/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.popups;

/**
 *
 * @author trwil
 */
public class AppointmentPopup extends javax.swing.JFrame {

    /**
     * Creates new form cPop
     */
    public AppointmentPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nLabel = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        aLabel = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        cLabel = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        sLabel = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        zLabel = new javax.swing.JLabel();
        z1 = new javax.swing.JTextField();
        saveP = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        sdLabel = new javax.swing.JLabel();
        edLabel = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(119, 120, 119));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nLabel.setText("Name:");
        getContentPane().add(nLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 67, -1, -1));

        n1.setText("jTextField1");
        n1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n1ActionPerformed(evt);
            }
        });
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 64, 195, -1));

        n2.setText("jTextField2");
        getContentPane().add(n2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 64, 195, -1));

        aLabel.setText("Address:");
        getContentPane().add(aLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, -1));

        a1.setText("jTextField3");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 118, 573, -1));

        a2.setText("jTextField7");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 156, 573, -1));

        cLabel.setText("City:");
        getContentPane().add(cLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 224, -1, 10));

        c1.setText("jTextField4");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 219, 197, -1));

        sLabel.setText("State:");
        getContentPane().add(sLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 275, -1, -1));

        s1.setText("jTextField5");
        getContentPane().add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 272, 197, -1));

        zLabel.setText("Zip:");
        getContentPane().add(zLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 332, -1, -1));

        z1.setText("jTextField6");
        getContentPane().add(z1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 329, 197, -1));

        saveP.setText("Save");
        getContentPane().add(saveP, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 399, 140, -1));

        jCheckBox1.setText("Residential");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 23, 96, -1));

        jCheckBox2.setText("Business");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 23, 99, -1));

        sdLabel.setText("Start Date:");
        getContentPane().add(sdLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 219, -1, 20));

        edLabel.setText("End Date:");
        getContentPane().add(edLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 272, -1, 20));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 219, 286, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 272, 286, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void n1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JLabel aLabel;
    private javax.swing.JTextField c1;
    private javax.swing.JLabel cLabel;
    private javax.swing.JLabel edLabel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JLabel nLabel;
    private javax.swing.JTextField s1;
    private javax.swing.JLabel sLabel;
    private javax.swing.JButton saveP;
    private javax.swing.JLabel sdLabel;
    private javax.swing.JTextField z1;
    private javax.swing.JLabel zLabel;
    // End of variables declaration//GEN-END:variables
}
