/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.popups;

import cosc456_project.TritonDB;

/**
 *
 * @author trwil
 */
public class ManufacturerPopup extends javax.swing.JFrame {

    /**
     * Creates new form cPop
     */
    public ManufacturerPopup() {
        initComponents();
    }

    private void savePActionPerformed(java.awt.event.ActionEvent evt) {                                      
        var triton = TritonDB.getInstance();
        var mName = n1.getText();
      
        var mID = triton.selectMax("Manufacturer", "mID") + 1;
        triton.insertStringInto("Manufacturer", new String[]{"mID","mName"}, new String[]{mID, mName});
        
        setVisible(false);
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nLabel = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        saveP = new javax.swing.JButton();

        setBackground(new java.awt.Color(119, 120, 119));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nLabel.setText("Name:");
        getContentPane().add(nLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 192, -1, -1));

        n1.setText("jTextField1");
        getContentPane().add(n1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 189, 429, -1));

        saveP.setText("Save");
        getContentPane().add(saveP, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 290, 140, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField n1;
    private javax.swing.JLabel nLabel;
    private javax.swing.JButton saveP;
    // End of variables declaration//GEN-END:variables
}
