/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.popups;

/**
 *
 * @author trwil
 */
public class ServiceplanPopup extends javax.swing.JFrame {

    /**
     * Creates new form cPop
     */
    public ServiceplanPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdlabel = new javax.swing.JLabel();
        saveP = new javax.swing.JButton();
        edLabel = new javax.swing.JLabel();
        lcLabel = new javax.swing.JLabel();
        lc1 = new javax.swing.JTextField();
        spLabel = new javax.swing.JLabel();
        sp1 = new javax.swing.JTextField();
        bclabel1 = new javax.swing.JLabel();
        isAnnually = new javax.swing.JCheckBox();
        isQuarterly = new javax.swing.JCheckBox();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(119, 120, 119));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sdlabel.setText("Start Date:");
        getContentPane().add(sdlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 76, -1, -1));

        saveP.setText("Save");
        getContentPane().add(saveP, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 405, 140, -1));

        edLabel.setText("End Date:");
        getContentPane().add(edLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

        lcLabel.setText("Labor Cost:");
        getContentPane().add(lcLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 194, -1, -1));

        lc1.setText("jTextField1");
        lc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lc1ActionPerformed(evt);
            }
        });
        getContentPane().add(lc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 191, 429, -1));

        spLabel.setText("Service Plan Cost:");
        getContentPane().add(spLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 262, -1, -1));

        sp1.setText("jTextField1");
        sp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp1ActionPerformed(evt);
            }
        });
        getContentPane().add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 259, 429, -1));

        bclabel1.setText("Bill Cycle:");
        getContentPane().add(bclabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 321, -1, -1));

        isAnnually.setText("Annually");
        getContentPane().add(isAnnually, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 317, -1, -1));

        isQuarterly.setText("Quarterly");
        isQuarterly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isQuarterlyActionPerformed(evt);
            }
        });
        getContentPane().add(isQuarterly, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 317, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 70, 183, -1));
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 124, 183, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void sp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp1ActionPerformed

    private void lc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lc1ActionPerformed

    private void isQuarterlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isQuarterlyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isQuarterlyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bclabel1;
    private javax.swing.JLabel edLabel;
    private javax.swing.JCheckBox isAnnually;
    private javax.swing.JCheckBox isQuarterly;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JTextField lc1;
    private javax.swing.JLabel lcLabel;
    private javax.swing.JButton saveP;
    private javax.swing.JLabel sdlabel;
    private javax.swing.JTextField sp1;
    private javax.swing.JLabel spLabel;
    // End of variables declaration//GEN-END:variables
}
