/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.popups;

/**
 *
 * @author trwil
 */
public class TransactionPopup extends javax.swing.JFrame {

    /**
     * Creates new form cPop
     */
    public TransactionPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Alabel = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        saveP = new javax.swing.JButton();
        eqCost = new javax.swing.JLabel();
        eq1 = new javax.swing.JTextField();
        lcLabel = new javax.swing.JLabel();
        lc1 = new javax.swing.JTextField();
        spLabel = new javax.swing.JLabel();
        sp1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(119, 120, 119));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Alabel.setText("Appointment ID: ");
        getContentPane().add(Alabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 76, -1, -1));

        a1.setText("jTextField1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 73, 429, -1));

        saveP.setText("Save");
        getContentPane().add(saveP, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 317, 140, -1));

        eqCost.setText("Equipment Cost:");
        getContentPane().add(eqCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 130, -1, -1));

        eq1.setText("jTextField1");
        eq1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eq1ActionPerformed(evt);
            }
        });
        getContentPane().add(eq1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 127, 429, -1));

        lcLabel.setText("Labor Cost:");
        getContentPane().add(lcLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 194, -1, -1));

        lc1.setText("jTextField1");
        lc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lc1ActionPerformed(evt);
            }
        });
        getContentPane().add(lc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 191, 429, -1));

        spLabel.setText("Service Plan Cost:");
        getContentPane().add(spLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 262, -1, -1));

        sp1.setText("jTextField1");
        sp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp1ActionPerformed(evt);
            }
        });
        getContentPane().add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 259, 429, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a1ActionPerformed

    private void eq1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eq1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eq1ActionPerformed

    private void sp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp1ActionPerformed

    private void lc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lc1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alabel;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField eq1;
    private javax.swing.JLabel eqCost;
    private javax.swing.JTextField lc1;
    private javax.swing.JLabel lcLabel;
    private javax.swing.JButton saveP;
    private javax.swing.JTextField sp1;
    private javax.swing.JLabel spLabel;
    // End of variables declaration//GEN-END:variables
}
